name = ('Victor Hugo Gomes de Andrade')
idade = ('30 Anos de Idade')
profissao = ('Mecânico Industrial')
endereco = ('Rua Pedro Álvares Cabral, Nº10, Apartamento 201')
bairro = ('Centro')
cidade = ('Nilópolis/RJ')
hobby = ('Guitarrista')
email = ('victor.vh.andrade@gmail.com')
o_que_esta_fazendo = ('Estudando programação')
ec = ('Solteiro')

print(name)
print(idade)
print(profissao)
print(endereco)
print(bairro)
print(cidade)
print(hobby)
print(email)
print(o_que_esta_fazendo)
print(ec)

nome = input('Digite o seu nome completo: ')
idade = input('Digite a sua idade: ')
profissao = input('Digite a sua profissao: ')
endereço = input('Digite o seu endereço: ')
bairro = input('Digite o seu bairro: ')
cidade = input('Digite a sua cidade/UF: ')
hobby = input('Digite o seu hobby: ')
email = input('Digite o seu e-mail: ')
o_que_esta_fazendo = input('O que você tem feito? ')
ec = input('Digite seu estado civil: ')

print(name)
print(idade)
print(profissao)
print(endereco)
print(bairro)
print(cidade)
print(hobby)
print(email)
print(o_que_esta_fazendo)
print(ec)


